"""Initial schema

Revision ID: 305f5ab07c9b
Revises: 
Create Date: 2025-07-02 10:02:38.267259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305f5ab07c9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_silver_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gold_price', sa.Numeric(), nullable=False),
    sa.Column('silver_price', sa.Numeric(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=300), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('store_address', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone2', sa.BigInteger(), nullable=True),
    sa.Column('logo_filename', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_picture', sa.String(length=200), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String(length=200)), nullable=True),
    sa.Column('metal_type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('metal_purity', sa.Integer(), nullable=True),
    sa.Column('metal_quantity', sa.Float(), nullable=True),
    sa.Column('jarti', sa.Float(), nullable=True),
    sa.Column('jyala', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('store')
    op.drop_table('user')
    op.drop_table('gold_silver_rate')
    # ### end Alembic commands ###
